version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: /tmp/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "deploy/package-lock.json" }}
      - run:
          name: Install packages
          command: cd deploy && npm install
      - save_cache:
          paths:
            - deploy/node_modules
          key: dependencies-{{ checksum "deploy/package-lock.json" }}
      - save_cache:
          paths:
            - deploy
            - assets
          key: build-{{ .Branch }}-{{ .Revision }}
  deploy:
    docker:
      - image: circleci/node:10
    working_directory: /tmp/app
    steps:
      - restore_cache:
          keys:
            - build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install now
          command: sudo npm install --global --unsafe-perm now
      - run:
          name: Generate manifest and upload assets
          command: mkdir -p datadist && cd deploy && npm run bundle -- --src ../assets --bucket content.decentraland.zone --out ../datadist/assets.json --content-server content.decentraland.zone
      - run:
          name: Deploy to now.sh
          command: cd deploy && now alias $(now --scope decentraland --name avatar-assets --token $NOW_TOKEN ../datadist) avatar-assets --scope decentraland --token $NOW_TOKEN
workflows:
  version: 2
  build-deploy-release:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - deploy:
          requires:
            - build
