name: Test Deploy Assets to Zone

on:
  pull_request:

jobs:
  deploy-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: test/modify-asset

      - name: Fetch Master Branch
        run: |
          git fetch origin master:master

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          yarn
          yarn global add ts-node

      - name: Prepare Deployment
        run: |
          yarn run prepare "test/modify-asset" https://peer.decentraland.zone > script_output.txt
          DEPLOY_COMMAND=$(cat script_output.txt | grep 'COMMAND -' | sed 's/^.*COMMAND - //' | sed 's/--identityFilePath <identity-file> //')
          echo "DEPLOY_COMMAND=$DEPLOY_COMMAND" >> $GITHUB_ENV
          echo "Deployment command: $DEPLOY_COMMAND "

      # - name: Deploy Assets
      #   run: |
      #     eval ${{ env.DEPLOY_COMMAND }} --privateKey ${{ secrets.PRIVATE_KEY }} --publicKey ${{ secrets.PUBLIC_KEY }}